### PR TITLE
Refactor + style around Plugins

### PR DESCRIPTION
**Pull request by qexat**
# Pull Request

## Description

- Moved plugins to folders according to their author (fixes a deleted issue)
- Created a `genCommand` for future use (i.e. moving 3D image processing to plugins)
- Ran prettify

## How was it tested

- `npm run dev`

### Test configuration

- OS: Ubuntu 21.10
- Node: v16.6.0 (npm 8.3.2)

### CODE REVIEW

**Comment by qexat** [comment]
honestly, fuck off

**Comment by Geoxor** [comment]
i was gonna merge thisss

**Comment by qexat** [comment]
Yeah that's why the original PR waited 10 fucking days huh

**Comment by Geoxor** [comment]
😕

**Pull request closed without merging**
