### PR TITLE
Refactor + style around Plugins

### PR DESCRIPTION
**Pull request by qexat**
# Pull Request

## Description

- Moved plugins to folders according to their author (fixes a deleted issue)
- Created a `genCommand` for future use (i.e. moving 3D image processing to plugins)
- Ran prettify

## How was it tested

- `npm run dev`

### Test configuration

- OS: Ubuntu 21.10
- Node: v16.6.0 (npm 8.3.2)

### CODE REVIEW

**Comment by qexat** [comment]
Prettify trolled my first commit :whyyyyyyy:

**Comment by qexat** [comment]
@Geoxor hum

**Comment by Geoxor** [comment]
fix the conflictsss

**Comment by qexat** [comment]
💀

**Comment by qexat** [comment]
Closing this because of duplicated PR

**Pull request closed without merging**
